<?php
require_once __DIR__ . '/../config/db.php';

echo "Running Database Migrations...\n";

$migrationsDir = __DIR__ . '/migrations';
$files = glob($migrationsDir . '/*.sql');

sort($files);

$overallSuccess = true;
$dbDriver = strtolower(trim(getenv('DB_DRIVER') ?: 'mysql'));
$isPgsql = in_array($dbDriver, ['pgsql', 'postgres', 'postgresql'], true);

foreach ($files as $file) {
    echo "Applying: " . basename($file) . "... ";
    $sql = file_get_contents($file);
    
    // Split statements by semicolon
    $statements = array_filter(array_map('trim', explode(';', $sql)));
    
    $fileSuccess = true;
    foreach ($statements as $stmt) {
        if (empty($stmt)) continue;

        if ($isPgsql) {
            // Translate DDL syntax for PostgreSQL
            $stmt = preg_replace('/ENGINE\s*=\s*InnoDB/i', '', $stmt);
            $stmt = preg_replace('/DEFAULT\s+CHARSET\s*=\s*\w+/i', '', $stmt);
            $stmt = preg_replace('/COLLATE\s*=\s*\w+/i', '', $stmt);
            $stmt = preg_replace('/AUTO_INCREMENT\s+PRIMARY\s+KEY/i', 'GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', $stmt);
            $stmt = preg_replace('/AUTO_INCREMENT/i', 'GENERATED BY DEFAULT AS IDENTITY', $stmt);
            $stmt = preg_replace('/TINYINT\(\d+\)/i', 'INT', $stmt);
            $stmt = preg_replace('/ENUM\([^)]+\)/i', 'VARCHAR(50)', $stmt);
            $stmt = preg_replace('/DATETIME/i', 'TIMESTAMP', $stmt);
            $stmt = str_replace('`', '', $stmt);
        }

        try {
            $res = $conn->query($stmt);
            if ($res === false) {
                $err = $conn->error ?? 'Unknown error';
                // Ignore duplicate column or table or constraint warnings on re-runs
                if (preg_match('/(Duplicate|already exists|column .* of relation .* exists)/i', $err)) {
                    continue;
                }
                echo "\nERROR in statement: " . $err . "\nSQL: " . $stmt . "\n";
                $fileSuccess = false;
                break;
            }
        } catch (Throwable $e) {
            $msg = $e->getMessage();
            if (preg_match('/(Duplicate|already exists|column .* of relation .* exists)/i', $msg)) {
                continue;
            }
            echo "\nERROR in statement: " . $msg . "\nSQL: " . $stmt . "\n";
            $fileSuccess = false;
            break;
        }
    }
    
    if ($fileSuccess) {
        echo "SUCCESS\n";
    } else {
        $overallSuccess = false;
    }
}

echo "Migration process finished.\n";
if (!$overallSuccess) {
    exit(1);
}

