-- PostgreSQL Schema Definition for Online Examination & AI System
-- Complete translation from MySQL/MariaDB schema supporting Supabase Free Tier & pgvector.

CREATE EXTENSION IF NOT EXISTS vector;

-- Drop existing tables in reverse dependency order if executing full schema reset
DROP TABLE IF EXISTS ai_practice_answers CASCADE;
DROP TABLE IF EXISTS ai_practice_sessions CASCADE;
DROP TABLE IF EXISTS ai_document_chunks CASCADE;
DROP TABLE IF EXISTS ai_documents CASCADE;
DROP TABLE IF EXISTS ai_generated_questions CASCADE;
DROP TABLE IF EXISTS ai_generation_requests CASCADE;
DROP TABLE IF EXISTS exam_violations CASCADE;
DROP TABLE IF EXISTS violation_report CASCADE;
DROP TABLE IF EXISTS violations CASCADE;
DROP TABLE IF EXISTS student_answers CASCADE;
DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. Users Table
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'student')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reset_token VARCHAR(255) DEFAULT NULL,
    token_expiry TIMESTAMP DEFAULT NULL,
    reset_otp VARCHAR(6) DEFAULT NULL,
    otp_expiry TIMESTAMP DEFAULT NULL
);

-- 2. Exams Table
CREATE TABLE exams (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    duration INT NOT NULL, -- Minutes
    total_marks INT NOT NULL,
    marks_per_question INT NOT NULL DEFAULT 1,
    ai_generated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Questions Table
CREATE TABLE questions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id INT NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    option_a VARCHAR(255) DEFAULT NULL,
    option_b VARCHAR(255) DEFAULT NULL,
    option_c VARCHAR(255) DEFAULT NULL,
    option_d VARCHAR(255) DEFAULT NULL,
    correct_option CHAR(1) DEFAULT NULL,
    subject VARCHAR(100) DEFAULT 'General',
    topic VARCHAR(100) DEFAULT 'General',
    difficulty VARCHAR(10) DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    explanation TEXT DEFAULT NULL
);
CREATE INDEX idx_questions_exam_id ON questions(exam_id);

-- 4. Results Table
CREATE TABLE results (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    exam_id INT REFERENCES exams(id) ON DELETE CASCADE,
    score INT DEFAULT 0,
    tab_switch_count INT DEFAULT 0,
    taken_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_exam_attempt UNIQUE (user_id, exam_id)
);
CREATE INDEX idx_results_user_id ON results(user_id);
CREATE INDEX idx_results_exam_id ON results(exam_id);

-- 5. Student Answers Table
CREATE TABLE student_answers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT REFERENCES users(id) ON DELETE CASCADE,
    exam_id INT REFERENCES exams(id) ON DELETE CASCADE,
    question_id INT REFERENCES questions(id) ON DELETE CASCADE,
    answer VARCHAR(255) DEFAULT NULL,
    CONSTRAINT unique_student_question_ans UNIQUE (student_id, exam_id, question_id)
);

-- 6. Violations Table
CREATE TABLE violations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exam_id INT NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    violation_count INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. Violation Report Table
CREATE TABLE violation_report (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exam_id INT NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    violations INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_violation_report_user ON violation_report(user_id);
CREATE INDEX idx_violation_report_exam ON violation_report(exam_id);

-- 8. Exam Violations Table
CREATE TABLE exam_violations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exam_id INT NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    violation_count INT DEFAULT 0,
    auto_submitted BOOLEAN DEFAULT FALSE,
    last_violation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    violation_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_exam_violation_attempt UNIQUE (student_id, exam_id)
);

-- 9. AI Generation Requests Table
CREATE TABLE ai_generation_requests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) UNIQUE NOT NULL,
    admin_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exam_id INT DEFAULT NULL REFERENCES exams(id) ON DELETE SET NULL,
    subject VARCHAR(100) NOT NULL,
    topic VARCHAR(100) NOT NULL,
    difficulty VARCHAR(10) NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
    question_type VARCHAR(50) NOT NULL DEFAULT 'mcq',
    number_requested INT NOT NULL,
    additional_context TEXT DEFAULT NULL,
    model_used VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'success' CHECK (status IN ('success', 'failed')),
    error_message TEXT DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 10. AI Generated Questions Table
CREATE TABLE ai_generated_questions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    admin_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exam_id INT DEFAULT NULL REFERENCES exams(id) ON DELETE SET NULL,
    subject VARCHAR(100) NOT NULL,
    topic VARCHAR(100) NOT NULL,
    difficulty VARCHAR(10) NOT NULL DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    question_type VARCHAR(50) NOT NULL DEFAULT 'mcq',
    question TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option CHAR(1) NOT NULL,
    explanation TEXT DEFAULT NULL,
    generation_model VARCHAR(100) DEFAULT 'gpt-4o-mini',
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    rejection_reason VARCHAR(255) DEFAULT NULL,
    reviewed_by INT DEFAULT NULL REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ai_gen_q_status ON ai_generated_questions(status);
CREATE INDEX idx_ai_gen_q_req_id ON ai_generated_questions(request_id);

-- 11. AI Documents Table
CREATE TABLE ai_documents (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size INT NOT NULL DEFAULT 0,
    subject VARCHAR(100) NOT NULL DEFAULT 'General',
    topic VARCHAR(100) NOT NULL DEFAULT 'General',
    total_pages INT NOT NULL DEFAULT 1,
    total_chunks INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'ingested', 'failed')),
    error_message TEXT DEFAULT NULL,
    uploaded_by INT NOT NULL DEFAULT 1 REFERENCES users(id) ON DELETE SET DEFAULT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 12. AI Document Chunks Table (with pgvector embedding)
CREATE TABLE ai_document_chunks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INT NOT NULL REFERENCES ai_documents(id) ON DELETE CASCADE,
    chunk_index INT NOT NULL,
    page_number INT NOT NULL DEFAULT 1,
    chunk_text TEXT NOT NULL,
    chunk_hash VARCHAR(64) NOT NULL,
    embedding vector(384), -- 384-dimensional dense vector embeddings
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ai_doc_chunks_doc_id ON ai_document_chunks(document_id);

-- 13. AI Practice Sessions Table
CREATE TABLE ai_practice_sessions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR(100) NOT NULL,
    topic VARCHAR(100) NOT NULL,
    difficulty VARCHAR(10) NOT NULL DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    total_questions INT NOT NULL DEFAULT 5,
    status VARCHAR(20) NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed')),
    score INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ DEFAULT NULL
);
CREATE INDEX idx_ai_prac_student ON ai_practice_sessions(student_id);
CREATE INDEX idx_ai_prac_topic ON ai_practice_sessions(topic);
CREATE INDEX idx_ai_prac_status ON ai_practice_sessions(status);

-- 14. AI Practice Answers Table
CREATE TABLE ai_practice_answers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INT NOT NULL REFERENCES ai_practice_sessions(id) ON DELETE CASCADE,
    student_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_index INT NOT NULL DEFAULT 0,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option CHAR(1) NOT NULL,
    explanation TEXT DEFAULT NULL,
    subject VARCHAR(100) NOT NULL DEFAULT 'General',
    topic VARCHAR(100) NOT NULL DEFAULT 'General',
    difficulty VARCHAR(10) NOT NULL DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    student_answer CHAR(1) DEFAULT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ai_prac_ans_session ON ai_practice_answers(session_id);
CREATE INDEX idx_ai_prac_ans_student_topic ON ai_practice_answers(student_id, topic);
