-- Migration 004: Question-Specific Focused Study Notes Table
-- PostgreSQL / Supabase Free Tier Schema Conventions
-- Compatible with PostgreSQL (active cloud) & MySQL (local fallback)
-- Note: Do NOT execute automatically. Non-destructive schema migration.

CREATE TABLE IF NOT EXISTS question_study_notes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INT DEFAULT NULL REFERENCES questions(id) ON DELETE CASCADE,
    ai_question_id INT DEFAULT NULL REFERENCES ai_generated_questions(id) ON DELETE CASCADE,
    practice_answer_id INT DEFAULT NULL REFERENCES ai_practice_answers(id) ON DELETE CASCADE,
    subject VARCHAR(100) NOT NULL,
    topic VARCHAR(100) NOT NULL,
    concept_title VARCHAR(255) NOT NULL,
    notes_content TEXT NOT NULL,
    rag_sources JSONB DEFAULT '[]'::jsonb,
    is_grounded BOOLEAN NOT NULL DEFAULT FALSE,
    source_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_qsn_question UNIQUE (question_id),
    CONSTRAINT unique_qsn_ai_question UNIQUE (ai_question_id),
    CONSTRAINT unique_qsn_practice UNIQUE (practice_answer_id)
);

CREATE INDEX IF NOT EXISTS idx_qsn_question_id ON question_study_notes(question_id);
CREATE INDEX IF NOT EXISTS idx_qsn_ai_question_id ON question_study_notes(ai_question_id);
CREATE INDEX IF NOT EXISTS idx_qsn_practice_id ON question_study_notes(practice_answer_id);
CREATE INDEX IF NOT EXISTS idx_qsn_subject_topic ON question_study_notes(subject, topic);
